use std::any::Any;
use std::cell::RefCell;
use std::ops::DerefMut;
use std::rc::Rc;
use sqlx::any::AnyConnectOptions;
use sqlx::pool::PoolConnection;
use sqlx::{AnyConnection, AnyPool, Connection, Executor};

use crate::core::type_info::TypeInfo;
use super::idbset::{IDbSet, IDbSetAny};
use super::ihaz_id::IHazSqlId;
use super::model::SqlModel;

pub type ConnType = Rc<dyn Connection<Database = dyn sqlx::database::HasStatementCache, Options = AnyConnectOptions>>;

pub struct SqlFileDbSet<TEntity: 'static + PartialEq + Clone + IHazSqlId + SqlModel> {
    // the path to the sqlite database file
    file_path: String,
    // the factory method to create a new TEntity
    // factory_method: fn() -> TEntity,
    // the method to parse a row into a TEntity
    // parse_item_method: fn(row: &sqlx::any::AnyRow) -> sqlx::Result<TEntity>,
    // the method to convert a TEntity into parameters for insertion/update
    // entity_to_params_method: fn(v: &TEntity) -> Vec<Box<String>>,
    // SQL connection (wrapped in RefCell for interior mutability)
    // conn: RefCell<ConnType>,
    // Table name for this entity
    table_name: String,
    pool: AnyPool,
}

// #[async_trait::async_trait]
impl<TEntity: 'static + Clone + IHazSqlId + PartialEq + SqlModel> SqlFileDbSet<TEntity> {
    pub fn new(pool: AnyPool, file_path: String, table_name: String) -> Self {
        Self {
            file_path,
            pool,
            table_name,
            // _marker: std::marker::PhantomData,
        }
    }

    pub async fn open(file_path: String, table_name: String) -> Result<Self, sqlx::Error> {
        let pool = AnyPool::connect(&file_path).await?;
        
        // Initialize table
        let mut conn = pool.acquire().await?;
        sqlx::query(TEntity::create_table_sql())
            .execute(&mut *conn)
            .await?;

        Ok(Self {
            pool,
            file_path,
            table_name,
        })
    }

    pub async fn get_connection(&self) -> Result<AnyConnection, sqlx::Error> {
        self.pool.acquire().await.map(|conn| conn.detach())
    }

    // async fn query_entities(&self, query: &str) -> Result<Vec<TEntity>, sqlx::Error> {
    //     let mut conn = self.get_connection();
    //     sqlx::query_as::<_, TEntity>(query)
    //         .fetch_all(&mut *conn)
    //         .await
    // }

    fn initialize_table(conn: &ConnType, table_name: &str) -> Result<(), sqlx::Error> {
        // todo: make it autogenerated from attributes
        conn.execute(
            &format!(
                "CREATE TABLE IF NOT EXISTS {} (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    data TEXT NOT NULL
                )",
                table_name
            ),
            [],
        )?;
        Ok(())
    }

    // fn get_connection(&self) -> std::cell::RefMut<ConnType> {
    //     self.conn.borrow_mut()
    // }
}

impl<TEntity: 'static + Clone + PartialEq + IHazSqlId + SqlModel> SqlFileDbSet<TEntity> {
    // Helper method to execute a query and return entities
    async fn query_entities(&self, query: &str, params: &[String]) -> Vec<TEntity> {
        let mut conn = self.get_connection().await?;
        let mut stmt = conn.prepare(query).await?;
        
        let rows = stmt.query_map(params, |row| {
            (self.parse_item_method)(row)
        }).expect("Failed to execute query");
        
        rows.filter_map(|r| r.ok()).collect()
    }
}

impl<TEntity: 'static + Clone + PartialEq + IHazSqlId> IDbSetAny for SqlFileDbSet<TEntity> {
    fn add_any(&self, item: Box<dyn Any>) {
        self.add(item.downcast_ref::<TEntity>().expect("could not downcast"))
    }

    fn add_range_any(&self, items: Vec<Box<dyn Any>>) {
        self.add_range(items.iter().map(|x| x.downcast_ref::<TEntity>().unwrap().clone()).collect::<Vec<TEntity>>());
    }

    fn attach_any(&self, item: Box<dyn Any>) {
        let item: &TEntity = item.downcast_ref().expect("could not downcast");
        self.attach(item);
    }

    fn create_any(&self) -> Box<dyn Any> {
        Box::new(self.create())
    }

    fn find_any(&self) -> Vec<Box<dyn Any>> {
        self.find().iter().map(|x| Box::new(x.clone()) as Box<dyn Any>).collect::<Vec<Box<dyn Any>>>()
    }

    fn get_all_any(&self) -> Vec<Box<dyn Any>> {
        self.get_all().iter().map(|x| Box::new(x.clone()) as Box<dyn Any>).collect::<Vec<Box<dyn Any>>>()
    }

    fn remove_any(&self, item: Box<dyn Any>) {
        let item: &TEntity = item.downcast_ref().expect("could not downcast");
        self.remove(item);
    }

    fn remove_range_any(&self, items: Vec<Box<dyn Any>>) {
        self.remove_range(items.iter().map(|x| x.downcast_ref::<TEntity>().unwrap().clone()).collect())
    }

    fn as_any(&self, type_info: TypeInfo) -> &dyn Any {
        assert_eq!(self.type_id(), type_info.type_id);
        self
    }

    fn entity_type_info(&self) -> TypeInfo {
        IDbSet::entity_type_info(self)
    }

    fn entity_type_name(&self) -> &'static str {
        IDbSet::entity_type_name(self)
    }

    fn save_changes(&self) {
        // SQLite automatically commits when the connection is closed
    }
}

impl<TEntity: 'static + Clone + PartialEq + IHazSqlId> IDbSet<TEntity> for SqlFileDbSet<TEntity> {
    fn add(&self, item: &TEntity) {
        let params = (self.entity_to_params_method)(item);
        let param_refs: Vec<String> = params.iter().map(|p| &**p).collect();
        
        let mut conn = self.get_connection();
        conn.execute(
            &format!("INSERT INTO {} (data) VALUES (?)", self.table_name),
            param_refs.as_slice(),
        ).expect("Failed to insert item");
    }

    fn add_range(&self, items: Vec<TEntity>) {
        let mut conn = self.get_connection();
        let tx = conn.transaction(|txn| {
            for item in items {
                let params = (self.entity_to_params_method)(&item);
                let param_refs: Vec<String> = params.iter().map(|p| &**p).collect();
                
                txn.execute(
                    &format!("INSERT INTO {} (data) VALUES (?)", self.table_name),
                    param_refs.as_slice(),
                ).expect("Failed to insert item in range");
            }
        }).expect("Failed to begin transaction");
        
        tx.commit().expect("Failed to commit transaction");
    }

    fn attach(&self, item: &TEntity) {
        // For SQL, attach is similar to add, but you might want to check for existence first
        self.add(item);
    }

    fn create(&self) -> TEntity {
        (self.factory_method)()
    }

    fn find(&self) -> Vec<TEntity> {
        self.query_entities(
            &format!("SELECT * FROM {} LIMIT 1", self.table_name),
            &[],
        )
    }
    
    fn get_all(&self) -> Vec<TEntity> {
        self.query_entities(
            &format!("SELECT * FROM {}", self.table_name),
            &[],
        )
    }

    fn remove(&self, item: &TEntity) {
        let ids = item.get_sql_id();
        let mut conn = self.get_connection();
        conn.execute(
            &format!("DELETE FROM {} WHERE id = ?", self.table_name),
            // params![ids],
        ).expect("Failed to remove item");
    }

    fn remove_range(&self, items: Vec<TEntity>) {
        let mut conn = self.get_connection();
        let tx = conn.transaction(|txn| {
            for item in items {
                let id = item.get_sql_id();
                txn.execute(
                    &format!("DELETE FROM {} WHERE id = ?", self.table_name),
                    // params![id],
                ).expect("Failed to remove item in range");
            }
        }).expect("Failed to begin transaction");
        
        tx.commit().expect("Failed to commit transaction");
    }

    fn entity_type_info(&self) -> TypeInfo {
        TypeInfo::of::<TEntity>()
    }

    fn entity_type_name(&self) -> &'static str {
        nameof::name_of_type!(TEntity)
    }

    fn upcast(&self) -> &dyn IDbSetAny {
        self
    }
}